package com.ultraprocessed.sync

import com.ultraprocessed.core.Http
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Wire format for the QR-pairing payload generated by the dashboard's
 * Settings page. One scan supplies everything the phone needs to start
 * syncing.
 */
@Serializable
data class PairPayload(
    @SerialName("v") val version: Int = 1,
    val url: String,
    val token: String,
    @SerialName("device_id") val deviceId: Int? = null,
    @SerialName("user_id") val userId: Int? = null
)

/**
 * Best-effort parse: returns null if the input doesn't look like our
 * payload (so the camera can keep scanning past random QR codes).
 */
fun parsePairPayload(raw: String): PairPayload? {
    val trimmed = raw.trim()
    if (!trimmed.startsWith("{")) return null
    return runCatching {
        Http.Json.decodeFromString(PairPayload.serializer(), trimmed)
    }.getOrNull()?.takeIf {
        it.url.isNotBlank() && it.token.isNotBlank()
    }
}
